### PR TITLE
Sprint 1/issue 4#text input component

### LINKED ISSUE #4: Text input component
## REQUIREMENTS / DESCRIPTION
A text input component that can be used in any part of the app, should receive as a prop the value, onChange function and some styles props to be rehusable

## DESIGN

image

### PR DESCRIPTION
**Pull request by Axw3ll**
# Text input component
Creation of a component that allows us to reuse the TextInput at all times, changing some parameters to adapt it to our needs, receiving parameters (onChangeText, value, styles, etc)

Create a file called Text input Styles in the Styles folder so that you can separate the styles that will never change and leave the styles that depend on a parameter fixed inside the component

## Screenshots
imagen

### CODE REVIEW

**Review by DerekAyala — APPROVED** [review]
GREAT JOB

**Review by Lizzflores — APPROVED** [review]
LGTM! maybe just use prettier for a better indentation :DD

**Comment by Antonio3veces3** [comment]
Excelente trabajo!

**Review by Eduardoespl — APPROVED** [review]
LGTM! 🚀

**Review by BrandonVG — APPROVED** [review]

**Pull request merged**
